site_name: Backend Fresher Guide
nav:
  - Home: index.md
  - Training Levels:
    - Simple: 1. simple/index.md
    - Medium: 2. medium/index.md
    - Hard: 3. hard/index.md
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  custom_dir: styles/
extra_css:
  - extra.css